name: Run Python Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      packages: read 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: |
          echo "DOCKER_RUN=\"docker run -v $GITHUB_WORKSPACE:/fisheye --rm ghcr.io/mrjoe3012/fisheye-python:latest\" >> $GITHUB_ENV &&
          $DOCKER_RUN /bin/sh -c ". /venv/bin/activate && pip install -e /fisheye/fisheye_python"

      - name: Pylint
        run: |
          $DOCKER_RUN /bin/sh -c ". /venv/bin/activate && pylint /fisheye/fisheye_python/"

      - name: MyPy
        run: |
          $DOCKER_RUN /bin/sh -c ". /venv/bin/activate && mypy /fisheye/fisheye_python/"

      - name: Pytest
        run: |
          $DOCKER_RUN /bin/sh -c ". /venv/bin/activate && pytest /fisheye/fisheye_python/tests"
